### ISSUE TITLE
댓글 관련 라우터 수정

### ISSUE THREAD

**Issue by SunEom** [AshRainK/SunStudy#81]
댓글 관련 라우터 응답 부분에 ordering이 오름차순로 되어있는데 내림차순으로 변경해야될 것 같습니다.

또한 다른 라우터에서 날짜 관련 Order를 설정할 때에 대부분의 경우 내림차순으로 변경해야 하므로 확인바랍니다.

**Comment by AshRainK** [comment]
조치 완료 하였습니당
